name: 'Sync Tech Radar Cursor Rules'
description: 'Automatically sync technology radar decisions as Cursor IDE rules to guide AI assistants'
author: 'Your Organization'
branding:
  icon: 'compass'
  color: 'blue'

runs:
  using: 'composite'
  steps:
    - name: Checkout PR Head
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
        token: ${{ github.token }}

    - name: Download Radar Rules
      shell: bash
      run: |
        echo "ðŸ“ Syncing from Aetheron Tech Radar"
        
        # Create the rules directory structure
        mkdir -p .cursor/rules/radar
        
        # Download all quadrant rules
        curl -sL "https://radar.sandbox.aetheron.com/.cursor/rules/radar/infrastructure.md" -o ".cursor/rules/radar/infrastructure.md"
        curl -sL "https://radar.sandbox.aetheron.com/.cursor/rules/radar/languages-frameworks.md" -o ".cursor/rules/radar/languages-frameworks.md"
        curl -sL "https://radar.sandbox.aetheron.com/.cursor/rules/radar/services-llms.md" -o ".cursor/rules/radar/services-llms.md"
        curl -sL "https://radar.sandbox.aetheron.com/.cursor/rules/radar/tools-methodologies.md" -o ".cursor/rules/radar/tools-methodologies.md"
        
        echo "âœ… Radar rules synced"

    - name: Check for Changes
      id: check-changes
      shell: bash
      run: |
        if git diff --quiet .cursor/rules/radar/; then
          echo "changed=false" >> $GITHUB_OUTPUT
        else
          echo "changed=true" >> $GITHUB_OUTPUT
        fi

    - name: Commit Changes
      if: steps.check-changes.outputs.changed == 'true'
      shell: bash
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add .cursor/rules/radar/
        git commit -m "ðŸ¤– Sync cursor rules from tech radar"
        git push origin HEAD:${{ github.head_ref }}

    - name: Comment on PR
      if: steps.check-changes.outputs.changed == 'true'
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'ðŸ¤– **Tech Radar Rules Updated**\n\nI\'ve synced the latest technology radar rules to guide our AI assistants. The updates are in `.cursor/rules/radar/`.'
          })
